language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - NUMPY_VERSION=1.16.6
  - NUMPY_VERSION=1.17.5
  - NUMPY_VERSION=1.18.5
  - NUMPY_VERSION=1.19.2
before_install:
  - pip install poetry
install:
  - poetry install
  - pip install -q numpy==$NUMPY_VERSION
script:
  - pytest
